#######################
# Adjustable Parameters
#######################

CC_PROG = gcc
ST_PROG = strip
ST_OPTS = -s
OBJS    = shell.o usage.o
PROG    = svn-shell
CFLAGS  = -Wall -O3
LDFLAGS = -static

#######################
# Compile-time options
#######################

ifndef PREFIX
  PREFIX = /usr
endif

# TARGET should be the prefix of a cross-compilation toolchain in your path
ifdef TARGET
	CC = $(TARGET)-$(CC_PROG)
  STRIP = $(TARGET)-$(ST_PROG)
else
	CC = $(CC_PROG)
  STRIP = $(ST_PROG)
endif

#######################
# Platform-specific
#######################

ifeq ($(shell uname),Darwin)
	LDFLAGS =
	ST_OPTS =
endif

#######################
# Make rules
#######################

all:	$(PROG)

$(PROG):	$(OBJS) 
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROG) $(OBJS) 
	$(STRIP) $(ST_OPTS) $(PROG)

clean:
	rm -f $(PROG) *.o

install: $(PROG)
	mkdir -p $(PREFIX)/bin
	install -m 0755 $(PROG) $(PREFIX)/bin/$(PROG)

#######################
# Dependency resolution
#######################

depend:	$(MAKES)
	(sed '1,/^# Below this line/!d' Makefile;	$(CC) -E -MM *.c) >$$$$ && mv $$$$ Makefile

# Below this line is generated by 'make depend' 
shell.o: shell.c cache.h
usage.o: usage.c cache.h
